spring:
  application:
    name: user-service   # 应用名，对应 Nacos 配置文件的 dataId 前缀
  config:
    import: optional:nacos:user-service.yml

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848   # Nacos 服务地址
      username: nacos
      password: nacos
