spring:
  application:
    name: user-service   # 应用名，对应 nacos 配置文件 user-service.yml
  config:
    import: nacos:user-service.yml # 从 nacos 加载 user-service.yml

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848   # Nacos 服务地址
      username: nacos               # 登录用户名
      password: nacos               # 登录密码
      config:
        group: DEFAULT_GROUP        # 配置分组
        file-extension: yml         # 配置文件后缀
